from app import db

class Player(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(80), unique=True, nullable=False)
    password = db.Column(db.String(128), nullable=False)
    lags_won = db.Column(db.Integer, default=0)
    eightball_stats = db.relationship('EightballStats', backref='player', lazy=True)
    nineball_stats = db.relationship('NineballStats', backref='player', lazy=True)

class GameState(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    player1_id = db.Column(db.Integer, db.ForeignKey('player.id'), nullable=False)
    player2_id = db.Column(db.Integer, db.ForeignKey('player.id'), nullable=False)
    game_type = db.Column(db.String(20), nullable=False)
    current_state = db.Column(db.Text, nullable=False)
    status = db.Column(db.String(20), nullable=False, default='in_progress')

    player1 = db.relationship('Player', foreign_keys=[player1_id])
    player2 = db.relationship('Player', foreign_keys=[player2_id])
class EightballStats(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    player_id = db.Column(db.Integer, db.ForeignKey('player.id'), nullable=False)
    skill_level = db.Column(db.Integer)
    match_sn_history = db.Column(db.Text)
    racks_to_win = db.Column(db.Integer)
    inning_total = db.Column(db.Integer)
    matches_played = db.Column(db.Integer)
    matches_won = db.Column(db.Integer)
    win_percentage = db.Column(db.Float)
    racks_won = db.Column(db.Integer)
    points_total = db.Column(db.Integer)
    points_per_match = db.Column(db.Float)
    points_available = db.Column(db.Float)
    defensive_shot_total = db.Column(db.Integer)
    defensive_shot_average = db.Column(db.Float)
    eight_on_the_break = db.Column(db.Integer)
    break_and_run = db.Column(db.Integer)
    mini_slam = db.Column(db.Integer)

class NineballStats(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    player_id = db.Column(db.Integer, db.ForeignKey('player.id'), nullable=False)
    skill_level = db.Column(db.Integer)
    match_sn_history = db.Column(db.Text)
    points_to_win = db.Column(db.Integer)
    inning_total = db.Column(db.Integer)
    matches_played = db.Column(db.Integer)
    matches_won = db.Column(db.Integer)
    win_percentage = db.Column(db.Float)
    match_ball_count = db.Column(db.Integer)
    points_total = db.Column(db.Integer)
    points_per_match = db.Column(db.Float)
    points_available = db.Column(db.Float)
    defensive_shot_total = db.Column(db.Integer)
    defensive_shot_average = db.Column(db.Float)
    nine_on_the_snap = db.Column(db.Integer)
    break_and_run = db.Column(db.Integer)
    mini_slam = db.Column(db.Integer)
